version: "3"

services:
  fastapi1:
    image: fastapi:latest
    container_name: fastapi1
    ports:
      - "8003:8002"

  fastapi2:
    image: fastapi:latest
    container_name: fastapi2
    ports:
      - "8004:8002"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
