version: "3"

services:
  fastapi1:
    image: fastapi-app:latest
    container_name: fastapi1
    ports:
      - "8003:8002"  # Exposing 8003 on host for fastapi1

  fastapi2:
    image: fastapi-app:latest
    container_name: fastapi2
    ports:
      - "8004:8002"  # Exposing 8004 on host for fastapi2

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
